import Head from 'next/head'
//import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Header from '../components/headerComponent'
import BodyHeader from '../components/bodyHeaderComponent'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>

      <main className={styles.mainHome}>
        <BodyHeader></BodyHeader>
      </main>

      <footer>
       FEET FEET
      </footer>
    </div>
  )
}
